version: '3'
services:
  web:
    build: .
    ports:
      - '8000:80'
    volumes:
      - cache_volume:/var/cache/nginx
    depends_on:
      - app1
      - app2
  app1:
    build: ./app1
  app2:
    build: ./app2
volumes:
  cache_volume:
